language: generic 
sudo: required
services:
  - docker


before_install:
  - docker build -t mickiehsu2008/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mickiehsu2008/react-test npm test

after_success:
  - docker build -t mickiehsu2008/multi-client ./client
  - docker build -t mickiehsu2008/multi-server ./server
  - docker build -t mickiehsu2008/multi-worker ./worker
  - docker build -t mickiehsu2008/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mickiehsu2008/multi-client
  - docker push mickiehsu2008/multi-server
  - docker push mickiehsu2008/multi-worker
  - docker push mickiehsu2008/multi-nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-410979977782
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
